//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.13 at 08:39:35 AM CEST 
//


package io.github.mufasa1976.springframework.webservice.example.xsd;

import java.time.LocalDate;
import javax.xml.bind.annotation.adapters.XmlAdapter;

public class Adapter1
    extends XmlAdapter<String, LocalDate>
{


    public LocalDate unmarshal(String value) {
        return (io.github.mufasa1976.springframework.webservice.example.util.LocalDateAdapter.unmarshal(value));
    }

    public String marshal(LocalDate value) {
        return (io.github.mufasa1976.springframework.webservice.example.util.LocalDateAdapter.marshal(value));
    }

}
