//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.11 at 10:03:12 PM CEST 
//


package io.github.mufasa1976.springframework.webservice.example.xsd;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the io.github.mufasa1976.springframework.webservice.example.xsd package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Books_QNAME = new QName("urn:books", "books");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: io.github.mufasa1976.springframework.webservice.example.xsd
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BooksForm }
     * 
     */
    public BooksForm createBooksForm() {
        return new BooksForm();
    }

    /**
     * Create an instance of {@link BookForm }
     * 
     */
    public BookForm createBookForm() {
        return new BookForm();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BooksForm }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:books", name = "books")
    public JAXBElement<BooksForm> createBooks(BooksForm value) {
        return new JAXBElement<BooksForm>(_Books_QNAME, BooksForm.class, null, value);
    }

}
