//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.11 at 10:03:12 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:books")
package io.github.mufasa1976.springframework.webservice.example.xsd;
