//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.12 at 09:02:09 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://mufasa1976.github.io/webservice/helloWorld", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package io.github.mufasa1976.springframework.webservice.example.xsd;
